import { useEffect, useState } from 'react';
import { ArrowRight, Check, CheckCircle2, ChevronRight, Clock3, Download, Flag, Pause, Pencil, Play, Plus, RotateCcw, Target, Trash2 } from 'lucide-react';
import { adaptMenu, canDo, drills, getDrill, menus, placeNames, type Menu, type Place, type Preferences } from './content';
import { Illustration } from './Illustration';
import { elapsed, localDate, startPractice, type Active, type DrillResult, type PracticeRecord } from './storage';
import { Empty, FigureCard, Meta, Modal, PageHeading, PlaceIcon, SectionHeading, navigate, useApp } from './ui';

export function menuForDrill(id:string,p:Preferences):Menu|null {
  const d=drills.find(x=>x.id===id);
  if(!d||!canDo(id,p))return null;
  return {id:`drill-${id}`,title:d.title,place:p.place,minutes:p.minutes,steps:[{title:'周囲の確認・軽い準備',minutes:1,description:d.condition},{title:d.title,minutes:p.minutes-2,drillId:d.id},{title:'今日の振り返り',minutes:1,description:'できたことと、次に試したいことを振り返りましょう。'}]};
}
function resolveMenu(id:string,p:Preferences){return id.startsWith('drill-')?menuForDrill(id.slice(6),p):menus.find(m=>m.id===id)?adaptMenu(menus.find(m=>m.id===id)!,p):null;}
function defaultCondition(id:string,p:Preferences) {
  const club=p.equipment.includes('iron')?'アイアン':p.equipment.includes('wedge')?'ウェッジ':'ドライバー';
  if(id==='D05')return `距離${Math.min(1,p.maxPutt)}m・${p.cup?'カップ':'停止エリア30cm四方'}`;
  if(id==='D06'){const max=Math.min(3,p.maxPutt);return `距離${[max/3,max/3*2,max].map(n=>Number(n.toFixed(2))).join('・')}m・停止エリア30cm四方`;} 
  if(['D07','D08','D10','D12'].includes(id))return `${club}・${getDrill(id).measurement}`;
  return getDrill(id).measurement;
}
function createActive(menu:Menu,p:Preferences):Active {const active=startPractice(menu,p);active.results=active.results.map(r=>({...r,condition:defaultCondition(r.drillId,p)}));return active;}

export function PracticePage() {
  const {data,update}=useApp();const p=data.preferences;
  const available=menus.filter(m=>m.place===p.place&&m.minutes===p.minutes).map(m=>adaptMenu(m,p)).filter((m):m is Menu=>!!m);
  const visible=drills.filter(d=>d.place===p.place&&canDo(d.id,p));
  return <><PageHeading eyebrow="A LITTLE PRACTICE" title="今日、何を練習しよう？" description="場所と時間を選んで、今のあなたに合う練習を。"/>
    <section className="practice-filter"><div><span className="field-label">練習する場所</span><div className="segmented">{(['home','putt','range'] as Place[]).map(place=><button key={place} className={p.place===place?'active':''} aria-pressed={p.place===place} onClick={()=>void update(s=>({...s,preferences:{...s.preferences,place}}))}><PlaceIcon place={place}/>{placeNames[place]}</button>)}</div></div><div><span className="field-label">使える時間</span><div className="segmented">{([5,15,30] as const).map(minutes=><button key={minutes} className={p.minutes===minutes?'active':''} aria-pressed={p.minutes===minutes} onClick={()=>void update(s=>({...s,preferences:{...s.preferences,minutes}}))}>{minutes}分</button>)}</div></div><a className="text-link" href={`#/settings?back=${encodeURIComponent('/practice')}`}>道具・場所の条件を変更<ChevronRight size={16}/></a></section>
    <SectionHeading title="ぴったりの練習メニュー" sub="準備から振り返りまで、ひとつの流れに。"/>
    {available.length?<div className="menu-grid">{available.map(menu=><a href={`#/menu/${menu.id}`} key={menu.id} className="menu-card"><div className="menu-cover sage"><Illustration id={getDrill(menu.steps.find(s=>s.drillId)!.drillId!).figure} hand={p.hand}/><span className="menu-time">{menu.minutes}<small>MIN</small></span></div><div className="menu-copy"><span className="eyebrow">TODAY’S MENU</span><h3>{menu.title}</h3><p>{menu.steps.filter(s=>s.drillId).map(s=>s.title).join(' / ')}</p><div className="card-bottom"><Meta minutes={menu.minutes} place={menu.place}/><span className="circle-arrow"><ArrowRight size={17}/></span></div></div></a>)}</div>:<Empty title="使える道具を教えてください" description={p.place==='putt'?'パター・ボールと、目標やカップのある場所を設定するとメニューが表示されます。':'クラブ・ボールと、打球できる場所を設定するとメニューが表示されます。'} href={`/settings?back=${encodeURIComponent('/practice')}`} label="条件を設定する"/>}
    <SectionHeading title="ひとつのドリルに集中" sub="気になる練習を、単独でも。"/>
    <div className="drill-list">{visible.map(d=><a key={d.id} href={`#/menu/drill-${d.id}`} className="drill-row"><span className="drill-thumb"><Illustration id={d.figure} hand={p.hand}/></span><div><span className="eyebrow">DRILL {d.id.slice(1)}</span><h3>{d.title}</h3><p>{d.focus}</p><Meta minutes={d.minutes} place={d.place}/></div><ChevronRight size={19}/></a>)}</div>
    <p className="muted-note">時間と回数は目安です。小さく、無理なく、途中で終えても大丈夫。</p>
  </>;
}
export function MenuPage({id}:{id:string}) {
  const {data,update}=useApp();const p=data.preferences;
  const menu=resolveMenu(id,p),raw=id.startsWith('drill-')?drills.find(d=>d.id===id.slice(6)):menus.find(m=>m.id===id);
  const [starting,setStarting]=useState(false);
  if(!raw)return <Empty title="メニューが見つかりません" description="一覧から練習を選んでください。" href="/practice"/>;
  if(!menu)return <><PageHeading back="/practice" eyebrow="PRACTICE" title={raw.title}/><Empty title="この練習の条件を確認しよう" description={'condition' in raw?raw.condition:`${placeNames[raw.place]}のメニューです。場所と必要な道具を設定してください。`} href={`/settings?back=${encodeURIComponent(`/menu/${id}`)}`} label="道具・場所を設定"/></>;
  const firstId=menu.steps.find(s=>s.drillId)?.drillId;
  async function start(){if(data.active||!menu)return;setStarting(true);const ok=await update(s=>({...s,active:createActive(menu,s.preferences)}));setStarting(false);if(ok)navigate('/session');}
  return <><PageHeading back="/practice" eyebrow="YOUR PRACTICE MENU" title={menu.title} description="ひとつずつ確かめて、今日の「できた」を。"/><Meta minutes={menu.minutes} place={menu.place}/><div className="menu-detail-grid"><section>{firstId&&<FigureCard id={getDrill(firstId).figure} hand={p.hand}/>}<div className="focus-banner"><Target size={20}/><div><span className="eyebrow">最初のポイント</span><p>{firstId&&getDrill(firstId).focus}</p></div></div></section><section className="paper-card"><SectionHeading title="今日の流れ" sub={`準備・休憩・振り返りを含めて${menu.minutes}分。`}/><ol className="timeline">{menu.steps.map((step,i)=><li key={i}><span className="timeline-number">{i+1}</span><div><h3>{step.title}</h3>{step.drillId&&<p>{getDrill(step.drillId).condition}</p>}{!step.drillId&&<p>{step.description}</p>}</div><span className="step-duration">{step.minutes}分</span></li>)}</ol>{data.active?<div className="notice">途中の練習があります。<a className="text-link" href="#/session">続きから再開<ArrowRight size={15}/></a></div>:<button className="primary full" disabled={starting} onClick={()=>void start()}><Play size={18}/>{starting?'準備しています…':'このメニューを始める'}</button>}<p className="muted-note">周囲と施設の利用条件を確認してから始めましょう。痛みが出たら動作をやめて休憩します。</p></section></div></>;
}
export function SessionPage() {
  const {data,update}=useApp(),a=data.active;
  const [now,setNow]=useState(Date.now());
  useEffect(()=>{const timer=setInterval(()=>setNow(Date.now()),1000);const visible=()=>setNow(Date.now());addEventListener('visibilitychange',visible);return()=>{clearInterval(timer);removeEventListener('visibilitychange',visible);};},[]);
  if(!a)return <Empty title="まだ練習を始めていません" description="気軽にできるメニューを選んでみましょう。" href="/practice"/>;
  const step=a.menu.steps[a.step],drill=step.drillId?getDrill(step.drillId):null;
  const resultIndex=a.menu.steps.slice(0,a.step+1).filter(s=>s.drillId).length-1;
  const result=drill?a.results[resultIndex]:null;
  const seconds=Math.floor(elapsed(a,now)/1000);
  function change(fn:(a:Active)=>Active){void update(s=>s.active?{...s,active:fn(s.active)}:s);}
  function pause(){change(active=>({...active,elapsedMs:elapsed(active),runningSince:active.runningSince===null?Date.now():null}));}
  async function finish(partial=false){const ok=await update(s=>s.active?{...s,active:{...s.active,elapsedMs:elapsed(s.active),runningSince:null}}:s);if(ok)navigate(`/finish${partial?'?partial=1':''}`);}
  return <><PageHeading eyebrow="ONE STEP AT A TIME" title={a.menu.title}/><div className="session-progress"><span>STEP {a.step+1} / {a.menu.steps.length}</span><div className="progress-track"><span style={{width:`${(a.step+1)/a.menu.steps.length*100}%`}}/></div><span className="timer" aria-label="練習経過時間"><Clock3 size={17}/>{String(Math.floor(seconds/60)).padStart(2,'0')}:{String(seconds%60).padStart(2,'0')}</span></div>
    <div className="session-layout"><section className="session-main"><div className="session-title"><span className="pill">目安 {step.minutes}分</span><h2>{step.title}</h2></div>{drill?<><FigureCard id={drill.figure} hand={a.preferences.hand}/><div className="focus-banner"><Target size={21}/><div><span className="eyebrow">いま意識することは、これだけ。</span><p>{drill.focus}</p></div></div><ol className="number-list">{drill.steps.map((s,i)=><li key={s}><span>{i+1}</span><p>{s}</p></li>)}</ol><div className="count-panel"><div><span className="field-label">まとめて実施回数を記録</span><p>目安 {drill.reps}回。毎回入力しなくて大丈夫。</p></div><div className="counter"><button aria-label="実施回数を1減らす" disabled={!result?.attempts} onClick={()=>change(active=>({...active,results:active.results.map((r,i)=>i===resultIndex?{...r,attempts:Math.max(0,r.attempts-1),success:r.success===null?null:Math.min(r.success,Math.max(0,r.attempts-1))}:r)}))}>−</button><output aria-label="実施回数">{result?.attempts||0}</output><button aria-label="実施回数を1増やす" onClick={()=>change(active=>({...active,results:active.results.map((r,i)=>i===resultIndex?{...r,attempts:Math.min(10000,r.attempts+1)}:r)}))}><Plus size={18}/></button><button className="add-ten" onClick={()=>change(active=>({...active,results:active.results.map((r,i)=>i===resultIndex?{...r,attempts:Math.min(10000,r.attempts+10)}:r)}))}>+10</button></div></div></>:<div className="session-rest"><Illustration id="address-front" hand={a.preferences.hand}/><p>{step.description}</p></div>}
    <div className="session-actions"><button className="secondary" disabled={a.step===0} onClick={()=>change(active=>({...active,step:Math.max(0,active.step-1)}))}>前の手順</button>{a.step===a.menu.steps.length-1?<button className="primary" onClick={()=>void finish()}>結果を記録<Check size={18}/></button>:<button className="primary" onClick={()=>change(active=>({...active,step:Math.min(active.menu.steps.length-1,active.step+1)}))}>次の手順<ArrowRight size={18}/></button>}</div></section>
    <aside className="session-aside paper-card"><h3>今日の流れ</h3><ol className="session-step-list">{a.menu.steps.map((s,i)=><li key={i} className={i===a.step?'active':i<a.step?'done':''}><span>{i<a.step?<Check size={13}/>:i+1}</span>{s.title}</li>)}</ol><button className="secondary full" onClick={pause}>{a.runningSince===null?<Play size={17}/>:<Pause size={17}/>} {a.runningSince===null?'練習を再開':'休憩する'}</button>{a.runningSince===null&&<p className="muted-note">タイマーを止めています。続きはいつでも再開できます。</p>}<button className="text-link full" onClick={()=>void finish(true)}>途中で終えて記録する<ArrowRight size={15}/></button><p className="muted-note">手順と入力は自動保存されます。画面ロック中の終了通知はありません。</p></aside></div></>;
}

interface DraftResult {drillId:DrillResult['drillId'];title:string;attempts:string;success:string;condition:string}
function RecordForm({record,onSave,label,onDraft}:{record:PracticeRecord;onSave:(record:PracticeRecord)=>Promise<boolean>;label:string;onDraft?:(draft:Pick<PracticeRecord,'results'|'rating'|'memo'>)=>void}) {
  const [results,setResults]=useState<DraftResult[]>(record.results.map(r=>({...r,attempts:String(r.attempts),success:r.success===null?'':String(r.success)}))),[rating,setRating]=useState(record.rating),[memo,setMemo]=useState(record.memo),[error,setError]=useState(''),[saving,setSaving]=useState(false);
  useEffect(()=>{
    if(!onDraft)return;
    const valid=results.every(r=>r.attempts!==''&&Number.isInteger(Number(r.attempts))&&Number(r.attempts)>=0&&Number(r.attempts)<=10000&&(r.success===''||(Number.isInteger(Number(r.success))&&Number(r.success)>=0&&Number(r.success)<=Number(r.attempts))));
    if(valid)onDraft({results:results.map(r=>({...r,attempts:Number(r.attempts),success:r.success===''?null:Number(r.success)})),rating,memo});
  },[results,rating,memo]);
  function patch(index:number,field:keyof Pick<DraftResult,'attempts'|'success'|'condition'>,value:string){setResults(results.map((r,i)=>i===index?{...r,[field]:value}:r));}
  async function submit(e:React.FormEvent){e.preventDefault();setError('');
    const parsed:DrillResult[]=[];
    for(const r of results){const attempts=Number(r.attempts),success=r.success===''?null:Number(r.success);if(r.attempts===''||!Number.isInteger(attempts)||attempts<0||attempts>10000||(success!==null&&(!Number.isInteger(success)||success<0||success>attempts))){setError('実施数は0〜10000の整数、成功数は実施数以下で入力してください。測っていない成功数は空欄で保存できます。');return;}parsed.push({...r,attempts,success});}
    setSaving(true);const ok=await onSave({...record,results:parsed,rating,memo});setSaving(false);if(!ok)setError('保存に失敗しました。入力を残しています。もう一度保存してください。');
  }
  return <form className="record-form" onSubmit={e=>void submit(e)}><div className="result-grid">{results.map((r,i)=><fieldset key={i} className="result-card"><legend>{r.title}</legend><p className="success-definition">{getDrill(r.drillId).success}</p><div className="number-fields"><label>実施数<input aria-label={`${r.title}の実施数`} type="number" inputMode="numeric" min="0" max="10000" step="1" required value={r.attempts} onChange={e=>patch(i,'attempts',e.target.value)}/></label><label>成功数 <small>任意</small><input aria-label={`${r.title}の成功数`} type="number" inputMode="numeric" min="0" max={r.attempts||0} step="1" placeholder="未計測" value={r.success} onChange={e=>patch(i,'success',e.target.value)}/></label></div><label className="condition-field">測った条件・距離・使ったクラブ<input aria-label={`${r.title}の条件`} maxLength={500} value={r.condition} onChange={e=>patch(i,'condition',e.target.value)}/></label></fieldset>)}</div><section className="paper-card"><span className="field-label">今日の手応え <small>任意</small></span><div className="rating-options">{([{id:'hard',label:'難しかった',symbol:'☁'},{id:'some',label:'少しできた',symbol:'◒'},{id:'good',label:'手応えあり',symbol:'☀'}] as const).map(r=><button key={r.id} type="button" aria-pressed={rating===r.id} className={rating===r.id?'active':''} onClick={()=>setRating(rating===r.id?null:r.id)}><span aria-hidden="true">{r.symbol}</span>{r.label}</button>)}</div><label className="memo-field">ひとことメモ <small>任意・1000文字まで</small><textarea value={memo} maxLength={1000} placeholder="例：ゆっくり構えたら、少し安定した。" onChange={e=>setMemo(e.target.value)}/></label></section>{error&&<p role="alert" className="form-error">{error}</p>}<button type="submit" disabled={saving} className="primary full"><Check size={18}/>{saving?'保存しています…':label}</button></form>;
}
export function FinishPage({partial}:{partial:boolean}) {
  const {data,update}=useApp();const a=data.active;
  if(!a)return <Empty title="記録は保存されました" description="練習帳で今日の一歩を振り返れます。" href="/records" label="記録を見る"/>;
  const record:PracticeRecord={id:a.id,startedAt:a.startedAt,localDate:a.localDate,timeZone:a.timeZone,menu:a.menu,contentVersion:a.contentVersion,elapsedMs:elapsed(a),results:a.results,rating:a.rating,memo:a.memo,status:partial?'partial':'complete'};
  async function save(record:PracticeRecord){const ok=await update(s=>({...s,records:[...s.records.filter(r=>r.id!==record.id),record],active:null}));if(ok)navigate(`/records/${record.id}`);return ok;}
  return <><PageHeading back="/session" eyebrow="NICE PRACTICE!" title="今日の一歩を、残そう。" description={partial?'途中で終えても、取り組んだことは立派な練習です。':'練習おつかれさま。測った結果だけ、気軽に記録しよう。'}/><div className="finish-summary"><CheckCircle2 size={29}/><div><h3>{a.menu.title}</h3><span>経過 {Math.floor(record.elapsedMs/60000)}分 · {partial?'途中終了':'完了'} · 成功数は未入力でも保存できます</span></div></div><RecordForm record={record} onSave={save} label="今日の練習を保存する" onDraft={draft=>{void update(s=>s.active?{...s,active:{...s.active,...draft}}:s);}}/></>;
}

export function RecordsPage({id}:{id?:string}) {
  const {data,update}=useApp();const [editing,setEditing]=useState(false),[deleting,setDeleting]=useState(false);
  const record=id?data.records.find(r=>r.id===id):undefined;
  if(id&&!record)return <Empty title="記録が見つかりません" description="練習帳の一覧から記録を選んでください。" href="/records" label="記録一覧"/>;
  if(record){const rating={hard:'難しかった',some:'少しできた',good:'手応えあり'};
    return <><PageHeading back="/records" eyebrow="YOUR PRACTICE NOTE" title={record.menu.title} description={`${record.localDate} · ${placeNames[record.menu.place]} · ${record.status==='partial'?'途中終了':'完了'}`}/>{editing?<RecordForm record={record} label="変更を保存する" onSave={async changed=>{const ok=await update(s=>({...s,records:s.records.map(r=>r.id===changed.id?changed:r)}));if(ok)setEditing(false);return ok;}}/>:<><div className="record-detail-summary"><div><Clock3 size={20}/><strong>{Math.round(record.elapsedMs/60000)}<small>分</small></strong><span>取り組んだ時間</span></div><div><Target size={20}/><strong>{record.results.reduce((n,r)=>n+r.attempts,0)}<small>回</small></strong><span>実施数の合計</span></div><div><Flag size={20}/><strong className="rating-text">{record.rating?rating[record.rating]:'未入力'}</strong><span>今日の手応え</span></div></div><div className="result-grid">{record.results.map((r,i)=><div className="result-card" key={i}><h3>{r.title}</h3><div className="record-numbers"><span>実施 <strong>{r.attempts}</strong></span><span>成功 <strong>{r.success===null?'未計測':r.success}</strong></span></div><p>{r.condition||'条件の記録なし'}</p><p className="muted-note">{getDrill(r.drillId).success}</p></div>)}</div>{record.memo&&<div className="paper-card"><span className="eyebrow">YOUR NOTE</span><p className="note-text">{record.memo}</p></div>}<div className="record-buttons"><button className="secondary" onClick={()=>setEditing(true)}><Pencil size={16}/>記録を編集</button><button className="danger-link" onClick={()=>setDeleting(true)}><Trash2 size={16}/>削除</button></div><a className="primary" href={`#/menu/${record.menu.id}`}><RotateCcw size={17}/>もう一度この練習をする</a></>}{deleting&&<Modal title="この記録を削除しますか？" onClose={()=>setDeleting(false)}><p>「{record.menu.title}」の記録を削除します。この操作は元に戻せません。</p><div className="modal-actions"><button className="secondary" onClick={()=>setDeleting(false)}>キャンセル</button><button className="danger" onClick={async()=>{const ok=await update(s=>({...s,records:s.records.filter(r=>r.id!==record.id)}));if(ok)navigate('/records');}}>削除する</button></div></Modal>}</>;
  }
  const records=[...data.records].sort((a,b)=>b.startedAt.localeCompare(a.startedAt));
  const days=Array.from({length:7},(_,i)=>{const date=new Date();date.setDate(date.getDate()-6+i);const key=localDate(date);return {key,label:`${date.getMonth()+1}/${date.getDate()}`,minutes:Math.round(records.filter(r=>r.localDate===key).reduce((n,r)=>n+r.elapsedMs,0)/60000)};});
  const max=Math.max(5,...days.map(d=>d.minutes));
  return <><PageHeading eyebrow="YOUR GOLF JOURNEY" title="小さな一歩の、練習帳。" description="できたことも、難しかったことも。全部が次につながる。"/><div className="record-stats"><div><strong>{records.length}<small>回</small></strong><span>これまでの練習</span></div><div><strong>{new Set(records.map(r=>r.localDate)).size}<small>日</small></strong><span>取り組んだ日数</span></div><div><strong>{Math.round(records.reduce((n,r)=>n+r.elapsedMs,0)/60000)}<small>分</small></strong><span>練習時間の合計</span></div></div>
    <section className="paper-card chart-card"><SectionHeading title="この7日間の練習" sub="少しずつ、続けていこう。"/><div className="week-chart" role="img" aria-label={days.map(d=>`${d.label} ${d.minutes}分`).join('、')}>{days.map(d=><div key={d.key}><span>{d.minutes}分</span><div className="chart-bar-track"><div className="chart-bar" style={{height:`${d.minutes?Math.max(5,d.minutes/max*100):2}%`}}/></div><small>{d.label}</small></div>)}</div></section>
    <SectionHeading title="練習の記録" href="/settings" link="データを書き出す"/>{records.length?<div className="record-list">{records.map(r=><a key={r.id} href={`#/records/${r.id}`} className="record-row"><span className="record-day"><strong>{r.localDate.slice(8)}</strong><small>{r.localDate.slice(5,7)}月</small></span><div><h3>{r.menu.title}</h3><span className="meta">{r.localDate} · {placeNames[r.menu.place]} · {r.status==='partial'?'途中終了':'完了'}</span>{r.memo&&<p>{r.memo}</p>}</div><span className="record-minute">{Math.round(r.elapsedMs/60000)}<small>分</small></span><ChevronRight size={18}/></a>)}</div>:<Empty title="最初の一歩を、記録しよう。" description="5分から始めてみませんか？練習を終えたら、この練習帳に残せます。" href="/practice"/>}<p className="muted-note">成功数は自分で観察した参考値です。異なる距離や条件の記録を、単純に比較しないようにしましょう。</p></>;
}
