import { useRef, useState } from 'react';
import { ArrowRight, Check, Download, Flag, Home, Info, Upload, WifiOff } from 'lucide-react';
import { equipmentNames, placeNames, type Equipment, type Place, type Preferences } from './content';
import { emptyData, exportBackup, mergeBackup, parseBackup, type Backup } from './storage';
import { InstallHelp } from './Learning';
import { Modal, PageHeading, PlaceIcon, SectionHeading, navigate, useApp } from './ui';

export function SettingsPage({setup=false,offlineReady=false}:{setup?:boolean;offlineReady?:boolean}) {
  const {data,update}=useApp(),[p,setP]=useState<Preferences>({...data.preferences,equipment:[...data.preferences.equipment]}),[message,setMessage]=useState(''),[error,setError]=useState(''),[install,setInstall]=useState(false),[deleting,setDeleting]=useState(false),[backup,setBackup]=useState<Backup|null>(null),[replace,setReplace]=useState(false),[saving,setSaving]=useState(false);
  const fileInput=useRef<HTMLInputElement>(null);
  const returnPath=new URLSearchParams(location.hash.split('?')[1]||'').get('back')||'/';
  const standalone=matchMedia('(display-mode: standalone)').matches||('standalone' in navigator&&(navigator as Navigator & {standalone:boolean}).standalone);
  function patch<K extends keyof Preferences>(key:K,value:Preferences[K]){setP({...p,[key]:value});setMessage('');}
  async function save(e:React.FormEvent){e.preventDefault();setSaving(true);const ok=await update(s=>({...s,preferences:p,onboarded:true}));setSaving(false);if(ok){setMessage('練習の条件を保存しました。');if(setup||returnPath!=='/')navigate(returnPath);}}
  function download(){const blob=new Blob([exportBackup(data)],{type:'application/json'}),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=`hajimete-golf-${new Date().toISOString().slice(0,10)}.json`;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setMessage('書き出したファイルを、iPhoneの「ファイル」などに保存してください。');}
  async function inspect(file:File){setError('');try{if(file.size>10_000_000)throw new Error('ファイルは10MB以下にしてください。');setBackup(parseBackup(await file.text()));setReplace(false);}catch(e){setError(e instanceof Error?e.message:'ファイルを読み込めませんでした。');}if(fileInput.current)fileInput.current.value='';}
  async function importData(){if(!backup||data.active)return;setError('');const next=mergeBackup(data,backup,replace);const ok=await update(next);if(ok){setP({...next.preferences,equipment:[...next.preferences.equipment]});setBackup(null);setMessage('記録を取り込みました。');}}
  return <><PageHeading eyebrow={setup?'WELCOME TO YOUR GOLF JOURNEY':'YOUR PREFERENCES'} title={setup?'あなたに合う練習を。':'設定・データ管理'} description={setup?'場所と道具を教えてください。あとから変更できます。':'練習の条件と、大切な記録を整えよう。'} back="/"/>
    <form onSubmit={e=>void save(e)} className="preferences-form paper-card"><SectionHeading title="練習の条件" sub="施設の備付け道具も、使えるものとして選べます。"/><fieldset><legend>打つ側</legend><div className="segmented">{(['right','left'] as const).map(hand=><button type="button" key={hand} className={p.hand===hand?'active':''} aria-pressed={p.hand===hand} onClick={()=>patch('hand',hand)}>{hand==='right'?'右打ち':'左打ち'}</button>)}</div></fieldset><div className="preference-columns"><fieldset><legend>主な練習場所</legend><div className="segmented">{(['home','putt','range'] as Place[]).map(place=><button type="button" key={place} aria-pressed={p.place===place} className={p.place===place?'active':''} onClick={()=>patch('place',place)}><PlaceIcon place={place} size={17}/>{placeNames[place]}</button>)}</div></fieldset><fieldset><legend>使える時間</legend><div className="segmented">{([5,15,30] as const).map(minutes=><button type="button" key={minutes} className={p.minutes===minutes?'active':''} aria-pressed={p.minutes===minutes} onClick={()=>patch('minutes',minutes)}>{minutes}分</button>)}</div></fieldset></div><fieldset><legend>使える道具 <small>複数選択・なくてもOK</small></legend><div className="equipment-grid">{(Object.keys(equipmentNames) as Equipment[]).map(e=><label key={e} className={p.equipment.includes(e)?'equipment-option checked':'equipment-option'}><input type="checkbox" checked={p.equipment.includes(e)} onChange={event=>patch('equipment',event.target.checked?[...p.equipment,e]:p.equipment.filter(x=>x!==e))}/>{equipmentNames[e]}{p.equipment.includes(e)&&<Check size={15}/>}</label>)}</div></fieldset>
    {p.place==='putt'&&<fieldset className="place-details"><legend>パットする場所の条件</legend><label className="native-check"><input type="checkbox" checked={p.cup} onChange={e=>patch('cup',e.target.checked)}/>カップがある</label><label className="native-check"><input type="checkbox" checked={p.multipleDistances} onChange={e=>patch('multipleDistances',e.target.checked)}/>複数の距離で練習できる</label><label className="distance-field">確保できる最長距離（m）<input type="number" inputMode="decimal" min="0.3" max="20" step="0.1" required value={p.maxPutt} onChange={e=>patch('maxPutt',e.target.value===''?0:Number(e.target.value))}/></label><p className="muted-note">平らに転がせる場所を使います。マットは任意、目印はコインなどでも代用できます。</p></fieldset>}
    {p.place==='range'&&<fieldset className="place-details"><legend>施設の条件</legend><label className="native-check"><input type="checkbox" checked={p.approach} onChange={e=>patch('approach',e.target.checked)}/>アプローチが許可されている</label><p className="muted-note">打球できる施設で使うことを前提にします。ドライバーにはティーも必要です。</p></fieldset>}
    {p.place==='home'&&<div className="notice soft"><Home size={18}/>自宅の基本メニューは、ボールを打たず、クラブも振りません。</div>}
    <div className="settings-save"><button className="primary" type="submit" disabled={saving}>{saving?'保存しています…':setup?'この条件で始める':'条件を保存'}<ArrowRight size={17}/></button>{setup&&<button type="button" className="text-link" onClick={async()=>{const ok=await update(s=>({...s,onboarded:true}));if(ok)navigate('/');}}>あとで設定する</button>}</div></form>
    {message&&<p className="success-message" role="status"><Check size={17}/>{message}</p>}{error&&<p className="form-error" role="alert">{error}</p>}
    <div className="settings-bottom-grid"><section className="paper-card"><SectionHeading title="いつでも使える練習帳"/><div className="offline-state"><WifiOff size={25}/><div><h3>{offlineReady?'オフラインで利用できます':'教材の保存を確認中'}</h3><p>{offlineReady?'レッスン・図解・練習メニューを保存済みです。':'初回は通信が必要です。公開サイトで教材を読み込むと、保存完了をお知らせします。'}</p></div></div>{!standalone&&<button className="secondary" onClick={()=>setInstall(true)}><Flag size={17}/>ホーム画面への追加方法</button>}<p className="muted-note">記録はこの端末の保存領域にあります。Safariとホーム画面で共有されない場合は、書出し・取込みで移行してください。</p></section>
    <section className="paper-card"><SectionHeading title="大切な記録を、手元に。"/><p>機種変更やブラウザのデータ削除に備えて、定期的に書き出しておきましょう。</p><div className="data-actions"><button className="secondary" onClick={download}><Download size={17}/>JSONを書き出す</button><button className="secondary" disabled={!!data.active} onClick={()=>fileInput.current?.click()}><Upload size={17}/>JSONを取り込む</button><input ref={fileInput} className="visually-hidden" type="file" accept=".json,application/json" aria-label="バックアップJSON" onChange={e=>{const file=e.target.files?.[0];if(file)void inspect(file);}}/></div>{data.active&&<p className="muted-note">取込み・全削除は、練習を終了または途中保存してから使えます。</p>}<button className="danger-link" disabled={!!data.active} onClick={()=>setDeleting(true)}>すべての記録と設定を削除</button></section></div>
    <details className="credits paper-card"><summary><Info size={17}/>このアプリと教材について</summary><p>はじめてゴルフ 1.0.0。図解と練習メニューはオリジナル。初心者が基本を確認するための教材です。専門家による監修は未実施です。</p><p>参考教材：<a href="https://www.golfdigest.co.jp/beginner/" target="_blank" rel="noreferrer">GDO ゴルフ初心者ガイド</a>（2026-10-02確認）。細かい姿勢は体格・クラブに合わせて調整してください。</p></details>
    {install&&<InstallHelp onClose={()=>setInstall(false)}/>}
    {backup&&<Modal title="記録の取込みを確認" onClose={()=>setBackup(null)}><p>練習記録 {backup.records.length}件、読了 {backup.read.length}件を読み取りました。</p><label className="native-check"><input type="checkbox" checked={replace} onChange={e=>setReplace(e.target.checked)}/>既存データをすべて置き換える</label><p className="muted-note">{replace?'現在の設定と記録を置き換えます。必要なら先に書き出してください。':'通常は追加のみ。同じIDの記録は、現在のデータを優先します。'}</p><div className="modal-actions"><button className="secondary" onClick={()=>setBackup(null)}>キャンセル</button><button className={replace?'danger':'primary'} onClick={()=>void importData()}>{replace?'全置換して取り込む':'追加して取り込む'}</button></div></Modal>}
    {deleting&&<Modal title="すべてのデータを削除しますか？" onClose={()=>setDeleting(false)}><p>設定、読了、練習記録を削除します。元に戻せないため、必要なら先にJSONを書き出してください。</p><div className="modal-actions"><button className="secondary" onClick={()=>setDeleting(false)}>キャンセル</button><button className="danger" onClick={async()=>{const next=emptyData();const ok=await update(next);if(ok){setP(next.preferences);setDeleting(false);setMessage('この端末の設定と記録を削除しました。');}}}>すべて削除する</button></div></Modal>}
  </>;
}
